CREATE DATABASE mini_mlti_board;

USE mini_multi_board;

CREATE TABLE USER(
	id INT PRIMARY KEY AUTO_INCREMENT
	,u_id VARCHAR(20) NOT NULL 
	,u_pw VARCHAR(256) NOT NULL 
	,u_name VARCHAR(50) NOT NULL 
	,created_at DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP() 
	,update_at DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP()
	,delete_at DATETIME  
);

CREATE TABLE board (
	id INT PRIMARY KEY AUTO_INCREMENT
	,u_pk INT NOT NULL 
	,b_type CHAR(1) NOT NULL 
	,b_title VARCHAR(30) NOT NULL 
	,b_contents VARCHAR(1000) NOT NULL 
	,img_file VARCHAR(50)
	,created_at DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP() 
	,update_at DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP()
	,delete_at DATETIME  
	);
	
	
	CREATE TABLE boardname(
	id INT PRIMARY KEY AUTO_INCREMENT
	,b_type CHAR(1) NOT NULL 
	,b_name VARCHAR (15) NOT NULL 
	);