CREATE DATABASE mini_boardemployees;

USE mini_board;

CREATE TABLE boards(
	num INT PRIMARY KEY AUTO_INCREMENT
	,title VARCHAR(100) NOT null
	,content VARCHAR(1000) NOT null
	,create_at DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP 
	,delete_flg CHAR(1) NOT NULL DEFAULT '0'
	,delete_at DATETIME DEFAULT  NULL 
);	
